volumes:
  think:
    external: true
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      CORS_HOST: http://localhost:3000
      # CORS_HOST: http://192.168.1.220:3000
      DATABASE_URL: mongodb://root:password@mongo
      DATABASE_NAME: cards
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      SIGNING_KEY: 80f21f4e921ab28acd4d57f19rsds222014147bfd96115d7ddbe8f5e4bc32a55hj7b343d7f262487484d1247235369e38926pabaf1ec9p00p5baf79ddbb566a97e
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
  mongo:
    image: mongo:6
    volumes:
        - ./setup/mongodb:/docker-entrypoint-initdb.d
        - cards:/data/db
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_FASTAPI_SERVICE_API_HOST: http://localhost:8000
      # PUBLIC_URL: http://192.168.1.220:3000
      # REACT_APP_FASTAPI_SERVICE_API_HOST: http://192.168.1.220:8000
